### PR TITLE
Wafaa/add tensorboard bm template

### LINKED ISSUE #355: Add a new TensorBoard template for bare-metal clusters
The current tensorboard template works with GKE but does not work properly when tested on bare-metal clusters (ai lab cluster). the reason we need a new template for bare-metal is that bare-metal clusters doesn't support services of type LoadBalancer. so the way Ingress is setup, services are exposed and accessed are different in bare-metal clusters than it's in GKE.

### PR DESCRIPTION
**Pull request by WafaaT**
fixes #355 

If you aren't done, please add the `wip` label until you're ready for review.

If you are adding a new template or mlt command/flag ensure that is is documented in the [docs/features.md](https://github.com/IntelAI/mlt/tree/master/docs/features.md) file.

## Reviewer Checklist

 - [ ] Do you understand it?
 - [ ] Is it correct?
 - [ ] Is it safe?
 - [ ] Is it legally compliant?
 - [ ] Is it robust?
 - [ ] Is it simple?
 - [ ] Is it tested?
 - [ ] Is it documented?
 - [ ] Is the style consistent?

See [the reviewer guide](docs/reviews.md) for more detail on each check.

### CODE REVIEW

File: mlt-templates/tensorboard-bm/deploy.sh [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+# SPDX-License-Identifier: EPL-2.0
+#
+
+# check if the service is up and running, get the TB service host and launch it in the local browser
+
+if [ ! -z "$( kubectl get ing ${JOB_NAME} --namespace ${NAMESPACE} )" ]
+then
```
Comment (karthikvadla) [inline mlt-templates/tensorboard-bm/deploy.sh]: instead o f `! -z` you can just use `-n`

```-n is the opposite of -z. if [ -n "${1}" ] passes if the string is not null and not empty.```

File: mlt-templates/tensorboard-bm/k8s-templates/tbjob.yaml [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+  replicas: 1
+  template:
+    metadata:
+      labels:
+        mlt-app-name: $app
+    spec:
+      containers:
+        - image: $image
+          name: tensorflow
+          command : ["/bin/sh"]
```
Comment (karthikvadla) [inline mlt-templates/tensorboard-bm/k8s-templates/tbjob.yaml]: why we are naming container as `tensorflow`? 🤔

File: mlt-templates/tensorboard-bm/README.md [hunk 3]
```diff
@@ -0,0 +1,34 @@
+# TensorBoard MLT Application for Bare Metal Clusters
+
+A TensorBoard service in Kubernetes Bare Metal cluster.
+
```
[the remark this answers is not in the document]
Comment (karthikvadla) [reply mlt-templates/tensorboard-bm/README.md]: Just say `A TensorBoard service on Kubernetes`. Because template itself is for baremetal

File: mlt-templates/tensorboard-gke/requirements.txt [hunk 4]
```diff
@@ -0,0 +1 @@
+tensorflow==1.4.0
```
Comment (ashahba) [inline mlt-templates/tensorboard-gke/requirements.txt]: We are using `tensorflow==1.8.0` everywhere else. I think it's better to use that version for consistency 🙂

File: mlt-templates/tensorboard-bm/Makefile [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+#
+
+SHELL := /bin/bash
+
+.PHONY: \
+	build \
+	main \
+	status
+
+SHELL := /bin/bash
```
Comment (ashahba) [inline mlt-templates/tensorboard-bm/Makefile]: This line is duplicate

File: mlt-templates/tensorboard-bm/README.md [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+This template requires the path to the TensorFlow job logs and the user domain to be configured.
```
Comment (ashahba) [inline mlt-templates/tensorboard-bm/README.md]: maybe `the path to logs for Tensorflow job` instead

File: mlt-templates/tensorboard-bm/README.md [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+`mlt config set template_parameters.domain <value>`
+
+TensorBoard template works with different storage sources, and it's the user responsibility to allow the TensorBoard service to access the logs location.
+
+This template assumes that `jq` is installed. `jq` is used while launching TensorBoard to query the service host.
+
+### Steps to launch TensorBoard service using TensorBoard MLT template:
+
+1. Create a TensorBoard application using the TensorBoard MLT template.
+`mlt init tensorboard-app --template=tensorboard-bm --namespace=<value> --registry-<value>`
```
Comment (ashahba) [inline mlt-templates/tensorboard-bm/README.md]: It should be:
`mlt init tensorboard-app --template=tensorboard-bm --namespace=<value> --registry=<value>`

File: tests/e2e/test_templates.py [hunk 8]
```diff
@@ -45,7 +45,8 @@ def test_templates(self):
 http://pytorch.org/tutorials/intermediate/dist_tuto.html
 pytorch-distributed  A distributed PyTorch MNIST example run using the \
 pytorch-operator.
-tensorboard          A TensorBoard service in Kubernetes cluster.
+tensorboard-bm       A TensorBoard service in Kubernetes Bare Metal cluster.
```
Comment (ashahba) [inline tests/e2e/test_templates.py]: I would recommend calling this `tensorboard-prem` since not all on premiss deployments are on `Bare Metal` 🙂

File: tests/e2e/test_templates.py [hunk 9]
```diff
@@ -90,7 +91,8 @@ def test_local_templates(self):
...
```
Comment (ashahba) [inline tests/e2e/test_templates.py]: same as above

File: mlt-templates/tensorboard-bm/README.md [hunk 10]
```diff
@@ -0,0 +1,35 @@
+# TensorBoard MLT Application for Bare Metal Clusters
```
Comment (ashahba) [inline mlt-templates/tensorboard-bm/README.md]: maybe `On Premise Clusters`

File: tests/e2e/test_templates.py (hunk 8 above)
Comment (WafaaT) [reply tests/e2e/test_templates.py]: but this is for bare metal only not for all on premise deployments.

File: mlt-templates/tensorboard-bm/README.md (hunk 10 above)
Comment (s1113950) [reply mlt-templates/tensorboard-bm/README.md]: Those mean almost the same thing though, with `bare metal` including things that aren't technically `on prem`. I would keep the wording, but maybe @nqn or someone can weigh in?

File: mlt-templates/tensorboard-bm/README.md [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+
+A TensorBoard service in Kubernetes Bare Metal cluster.
+
+This template requires the path to the TensorFlow job logs and the user domain to be configured.
+The command below shows how to update the log directory value in `k8s-templates/tbjob.yaml`.
+
+`mlt config set template_parameters.logdir <value>` , and
+`mlt config set template_parameters.domain <value>`
+
+TensorBoard template works with different storage sources, and it's the user responsibility to allow the TensorBoard service to access the logs location.
```
Comment (s1113950) [inline mlt-templates/tensorboard-bm/README.md]: `user's`

File: mlt-templates/tensorboard-bm/README.md [hunk 12]
```diff
@@ -0,0 +1,35 @@
...
+### Steps to launch TensorBoard service using TensorBoard MLT template:
+
+1. Create a TensorBoard application using the TensorBoard MLT template.
+`mlt init tensorboard-app --template=tensorboard-bm --namespace=<value> --registry-<value>`
+
+`cd tensorboard-app` :
+
+2. Set TensorBoard `logdir` and `domain`.
+`mlt config set template_parameters.logdir <value>` and
+`mlt config set template_parameters.domain <value>`
```
Comment (s1113950) [inline mlt-templates/tensorboard-bm/README.md]: Can you document an example of the path and user domain?

File: mlt-templates/tensorboard-bm/README.md [hunk 13]
```diff
@@ -0,0 +1,35 @@
...
+
+3. Create the application image.
+`mlt build`
+
+4. Deploy TensorBoard service.
+`mlt deploy`,
+which deploys the TensorBoard service and launches the local browser with `http://<service-name>.domain`.
+It might take few seconds for the service to be up and running, so reload the page if Tensorbaord did not open right away.
```
Comment (s1113950) [inline mlt-templates/tensorboard-bm/README.md]: `TensorBoard`

File: mlt-templates/tensorboard-bm/parameters.json [hunk 14]
```diff
@@ -0,0 +1,6 @@
+{
+  "template_parameters" : [
+    { "name": "logdir", "value": "path_to_tensorboard_logs" },
```
Comment (s1113950) [inline mlt-templates/tensorboard-bm/parameters.json]: Could you put a sample path and domain here?
Something like `/tmp/tensorboardLogs` and `localhost` might suffice? Just so user has a working example

File: mlt-templates/tensorboard-gke/README.md [hunk 15]
```diff
@@ -9,14 +9,12 @@ The command below shows how to update the log directory value in `k8s-templates/
 
 TensorBoard template works with different storage sources, and it's the user responsibility to allow the TensorBoard service to access the logs location.
 
-This template assumes that Ingress controller is enabled in the Kubernetes cluster, and also that `jq` is installed. `jq` is used while launching TensorBoard to get the service IP address.
+This template assumes that Ingress controller is enabled in the Kubernetes cluster, but here Ingress is not needed as GKE can expose Kubernetes services using [GCP load balancer](https://cloud.google.com/kubernetes-engine/docs/how-to/exposing-apps). and also assumes that `jq` is installed. `jq` is used while launching TensorBoard to get the service IP address.
```
Comment (s1113950) [inline mlt-templates/tensorboard-gke/README.md]: 🤔 I got confused when I read this. So the template assumes that Ingress is enabled but also it's not needed? Should we just tell users that Ingress will be exposed by GKE and leave the other part out?

File: tests/e2e/test_deploy_flow.py [hunk 16]
```diff
@@ -52,10 +52,12 @@ def teardown(self):
                     # already deleted or were never created
                     pass
 
-    @pytest.mark.parametrize('template',
-                             filter(lambda x: os.path.isdir(
-                                 os.path.join('mlt-templates', x)),
-                                 os.listdir('mlt-templates')))
+    # TODO: find a way to test `tensorboard-bm`.
```
Comment (s1113950) [inline tests/e2e/test_deploy_flow.py]: Can you insert a link to an issue on github so we can track it?

File: mlt-templates/tensorboard-bm/README.md (hunk 12 above)
Comment (WafaaT) [reply mlt-templates/tensorboard-bm/README.md]: @s1113950 I cannot state my user domain or a path of the a training results for my account on `ai lab cluster` in the docs. however if we need to add a generic example shows how we configure the access to a data storage system in bare metal, I would do it later on on our team bare metal test cluster and I think also it can be in a separate PR.

File: mlt-templates/tensorboard-bm/parameters.json (hunk 14 above)
Comment (WafaaT) [reply mlt-templates/tensorboard-bm/parameters.json]: I think using `localhost` as a default value might be a bit confusing to the user. we provide a template to run TB in Kubernetes cluster and not locally (as MLT is at the client side). users should read the docs anyways..what do you think? also tensorboard doesn't complain if I didn't provide a valid `log_dir` value as in `tensorboard-gke`.

File: mlt-templates/tensorboard-gke/README.md (hunk 15 above)
Comment (WafaaT) [reply mlt-templates/tensorboard-gke/README.md]: yes, I will rephrase..

File: mlt-templates/tensorboard-bm/README.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (WafaaT) [reply mlt-templates/tensorboard-bm/README.md]: this line is meant to describe the template in `met template list` command, I think it should be bit descriptive.. `bm` might not be that clear!

File: mlt-templates/tensorboard-bm/parameters.json (hunk 14 above)
Comment (s1113950) [reply mlt-templates/tensorboard-bm/parameters.json]: But isn't this for a bare metal cluster? That means the cluster would run on `localhost` on one of the machines in their data center?.

File: mlt-templates/tensorboard-bm/README.md (hunk 12 above)
Comment (s1113950) [reply mlt-templates/tensorboard-bm/README.md]: You could use dummy values like `/tmp` and `http://my-domain.com` or something? Or do you think those are obvious? 🤔

File: mlt-templates/tensorboard-bm/README.md [hunk 17]
```diff
@@ -2,20 +2,20 @@
 
 A TensorBoard service in Kubernetes Bare Metal cluster.
 
-This template requires the path to the TensorFlow job logs and the user domain to be configured.
+This template requires the path to logs for TensorFlow job and the user domain to be configured.
```
Comment (s1113950) [inline mlt-templates/tensorboard-bm/README.md]: 🤔 What about this?
"This template requires configuration of both user domain and Tensorflow job logs path."

File: mlt-templates/tensorboard-bm/deploy.sh [hunk 18]
```diff
@@ -18,7 +18,7 @@
 
 # check if the service is up and running, get the TB service host and launch it in the local browser
 
-if [ -n "$( kubectl get ing ${JOB_NAME} --namespace ${NAMESPACE} )" ]
+if [ ! -z "$( kubectl get ing ${JOB_NAME} --namespace ${NAMESPACE} )" ]
```
Comment (s1113950) [inline mlt-templates/tensorboard-bm/deploy.sh]: Were you going to go with `-n` here instead?

**Comment by s1113950** [comment]
I would really like to have a way to test `tensorboard-bm`, but because it's expecting a bare metal cluster I'm not sure if it's possible 😞 @WafaaT I'm gonna approve though and we can have a ticket to follow up on how we'll test this.

File: tests/e2e/test_deploy_flow.py [hunk 19]
```diff
@@ -52,10 +52,12 @@ def teardown(self):
...
+    # `tensorboard-bm` template requires the user domain to be configured
+    # as a custom parameter https://github.com/IntelAI/mlt/issues/371
```
Comment (WafaaT) [inline tests/e2e/test_deploy_flow.py]: @ashahba I added the link here as for Steven comment

**Comment by WafaaT** [comment]
@s1113950 @ashahba  I already added the link to the MLT issue to find a way to test bare metal based templates here  as you asked before. https://github.com/IntelAI/mlt/blob/74f19de767dee66ad5d94801ce0591e4f468ca6f/tests/e2e/test_deploy_flow.py#L57
